config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources:posts
  get 'welcome/index' 
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy]

    
    def index
        @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page:1)
    end
    def new
        @post =Post.new
    end
    def create
        @post=Post.new post_params

    if @post.save 
        redirect_to @post, notice: "Hellz yeah, Busra! Your article was succesfully saved!"
    else
        render 'new', notice: "Oh no, Busra! I was unable to save your post."
    end
    end
    def show
    end
    def edit
    end
    def update
        if @post.update post_params
        redirect_to @post, notice: "Huzzah! Your article was succesfully saved!"
        else
            render 'edit'
        end
    end
    def destroy
        @post.destroy
        redirect_to posts_path
    end


    private
    def post_params
        params.require(:post).permit(:title, :content, :slug)
    end

    def find_post
        @post = Post.friendly.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        @posts = Post.all.limit(3).order("created_at desc")
    end
end

app/helpers/application_helper.rb
=begin
module ApplicationHelper
    
    class HTMLwithPygments < Redcarpet::Render::HTML
        def block_code(code, language)
            Pygments.highlight(code, lexer: language)
        end
    end

    def markdown(content)
        renderer= HTMLwithPygments. new(hard_wrap: true, filter_html: true)
        options={
            autolink:true,
            no_intra_emphasis:true,
            disable_intented_code_blocks: true,
            fenced_code_blocks: true,
            lax_html_blocks: true,
            strikethrough: true,
            superscript: true
          }
          Redcarpet::Markdown.new(renderer, options).render(content).html_safe
        end   
end
=end
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Busra Bahar - Stajyer Bilgisayar Muhendisi</title>

    
      <link href="//fonts.googleapis.com/css2?family=Raleway:wght@300;400;500;600;700&display=swap" rel="stylesheet" type='text/css'>

        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" >


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track'=> true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   <%= csrf_meta_tags %>

  </head>

  <body>
  <header id="main_navigation" class="clearfix"> 
            <%= link_to "Busra Bahar ", root_path, class: "name" %>
            <nav>
            <%= link_to "Makaleler", posts_path %>   
            <a href="projeler.html">Projeler</a>
            <a href="iletisim.html">Iletisim</a>
            <a href="">CV</a>
            </nav>
        </header>
    <%= yield %>
     <footer id="main_footer">
            <p class="copyright">&copy;2020 Busra Bahar</p>
            <nav>
                <a href="#"><i class = "fa fa-twitter"></i></a>
                <a href="https://www.linkedin.com/in/busrabahar/" target= "blank"><i class = "fa fa-linkedin"></i></a>
                <a href="http://github.com/busrabahar" target="blank" ><i class = "fa fa-github"></i></a>
            </nav>
        </footer>
  </body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script >
        var disqus_shortname = 'blogging-course-13';
        var disqus_identifier = '<%= @post.id %>';
        var disqus_title = ' <%= @post.title %>' ;
        var disqus_url = ' <%= url_for([@post, {only_path: false}]) %>';

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://blogging-course-13.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
                            

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<% if @post.errors.any? %>
    <h2><%=pluralize(@post.errors.count, "error") %> prevented this post from saving: </h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
        <% end %>
        </ul>
        <% end %>
        <%= f.label :title %> <br>
        <%= f.text_field :title %>
        <br>
        <br>
        <%= f.label :content, "Write your article here" %> <br>
        <%= f.text_area :content %>

        <br>
        <br>

        <%= f.submit %>

        <% end %>

app/views/posts/edit.html.erb
<h1>Edit Post </h1>

<%= render 'form' %>

app/views/posts/index.html.erb
 <h1 id= "page_title"> Yazdigim Seyler </h1>
 <div id="posts_wrapper" class="skinny_wrapper">
        <% @posts.each do |post| %>
        <div class="post">
            <p class="date"><%= post.created_at.strftime('%A, %B %d') %> </p>
            <h2><a href="#"><%= link_to post.title, post %></a></h2>
            <hr>
        </div>
        <% end %>
        </div>
       
       <%= will_paginate @posts %>

    

app/views/posts/new.html.erb
<h1> New Post </h1> 
<%= render 'form' %>    <!--kullanıcının yazdığı postu ekrana getirdik.-->

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
            <header>
                <p class="date"><%= @post.created_at.strftime ('%A, %B %d') %> </p>
                <h1> <%= @post.title %>
                <hr>
            </header>
            <div id="content">
            <%= simple_format @post.content %> <!--simple_format ile yazılan yazıya format verildi (paragraf seklinde)-->
            </div>
</div>

 <div id="share_box">
                <p>Yapilacaklar Listesi'ni Paylas!</p>
                

                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href=""><i class="fa fa-facebook"></i></a>
                <a href=""><i class="fa fa-google-plus"></i></a>
 </div>

<%= render 'disqus' %>
<br>

<%= link_to "Edit", edit_post_path(@post) %>
<%= link_to "Delete", post_path(@post), method: :delete,  data: { confirm: "Are you sure you want to delete this post?"} %>

app/views/welcome/index.html.erb
<div class="wrapper clearfix">
            <div class="col-1 homepage_content">
                <h2> Hakkinda</h2>
                <hr> <p>Merhaba, ben Busra! </p> <p>Sakarya Universitesi Bilgisayar Muhendisligi  4. sinif ogrencisiyim. </p><p>
                    Bu blogu egitim hayatim boyunca yapmis oldugum  <a href='#'> projeleri </a> ve calismis oldugum notlari paylasmak amaciyla aciyorum.
                </p>
                
            </div> 
            <div class="col-2 homepage_content">
                <h2>Yazdigim seyler</h2>
                <hr>
                
               <% @posts.each do |post| %>
                <h3><a href="#"> <%= link_to post.title , post %> </a> </h3>
                <p class="date"> <%= post.created_at.strftime("%A, %b %d") %> </p>
                <% end %>

                

            </div> 
            <div class="col-3 homepage_content">    
                <h2> Projelerim</h2>
                <hr>
                <h3><a href="#"></a>C# Asp.Net MVC Yemek Tarifi Sitesi</a></h3>
                <p class="date">10 Ocak Sali</p>
                <h3><a href="#"></a>C# Cicek Satis Otomasyonu </a></h3>
                <p class="date">1 Subat Pazar</p>
                <h3><a href="#"></a>IoT Tabanli Yangin Alarm Sistemi</a>/h3> 
                <p class="date">4 Mayis Sali</p>
                

            </div>
        </div>